
name: ecosistema

include:
  - ./services/proxy/docker-compose.yml
  - ./services/sistemas/docker-compose.yml
  - ./services/agendador-tarefas/docker-compose.yml
  - ./services/psvo/docker-compose.yml  
  - ./services/ava/docker-compose.yml
