api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https 
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
    http3: {}

providers:
  docker: {}
  file:
    filename: /etc/traefik/traefik_dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: diou.bernardo@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
