# stage de build
FROM node:latest AS build

WORKDIR /app

COPY ./app/package*.json ./
RUN npm install
COPY ./app ./
RUN npm run build

#stage de produção
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]