services:

  proxy:
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${TARGET:?}
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80/tcp" 
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
      - ../../certs:/certs
    environment:
      DOMINIO: ${DOMINIO:?}
    labels:
      traefik.enable: ${DESENVOLVIMENTO:?}
      traefik.http.routers.dashboard.rule: Host(`dashboard.${DOMINIO:?}`)
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.service: api@internal